use_frameworks!

platform :ios, '8.0'

target 'WHMyTest_Example' do
  pod 'WHMyTest', :path => '../'

  target 'WHMyTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
